开始菜单收回(隐藏)
win12-online/win12 pull request #499
Opened 2024-11-30 03:43 UTC by kjmjh

点击开始菜单以外的东西，开始菜单收回(隐藏)

2024-11-30 03:47 UTC, kjmjh reviewed
。

2024-11-30 04:18 UTC, lingbopro requested changes
emm，这个测试过吗

2024-11-30 04:18 UTC, lingbopro commented on desktop.js
> +page.addEventListener('click',()=>{
这个逻辑有大问题，直接对整个页面加监听器的话，点击开始菜单的点击事件最终还是会冒泡到这里，也就是说无论点哪里（包括开始菜单）时开始菜单都会关闭

2024-11-30 04:18 UTC, lingbopro commented on desktop.js
> +setupGlobalKey();
斯... whitespace changes 看着不舒服

2024-11-30 05:43 UTC, NB-Group commented
@lingbopro 这个代码可以吗？我懒得看了（）（）

2024-11-30 07:15 UTC, lingbopro commented
> @lingbopro 这个PR可以合吗？我懒得看了（）（）

可能不行，我没测试

2024-11-30 07:15 UTC, lingbopro commented
可以看眼我的评论，这个逻辑有问题

2024-11-30 07:36 UTC, kjmjh commented
测试了，但只是浅浅的

2024-11-30 07:38 UTC, kjmjh commented
改的不多，

2024-11-30 09:41 UTC, kjmjh commented
改好了，@lingbopro 看一下

2024-12-01 01:15 UTC, lingbopro approved these changes
目前看来（应该）没什么大问题，起码能用

2024-12-01 09:53 UTC, NB-Group commented
那我合并了

2024-12-01 09:53 UTC, merged

2024-12-01 10:02 UTC, kjmjh commented
豪嘞

2024-12-02 13:56 UTC, NB-Group commented
xswl，你这个PR属实逆天（）
我刚看了下，只有开始菜单能自动收回的。你要做就把搜索、小组件，控制中心和日历都做上啊（）

2024-12-02 17:27 UTC, ProgramCX commented
![动画](https://github.com/user-attachments/assets/48cf65ef-33ed-42a1-9a08-e9c5a85aa2cd)
为啥我点了桌面还有图标开始菜单没有隐藏😂

2024-12-06 09:31 UTC, kjmjh commented
> ![动画](https://github.com/user-attachments/assets/48cf65ef-33ed-42a1-9a08-e9c5a85aa2cd)
> 为啥我点了桌面还有图标开始菜单没有隐藏😂

？？？我这边可以啊？？？(Chrome和火狐都没问题)

2024-12-06 09:33 UTC, kjmjh commented
我还用学校微机室的ly电脑试了，没问题

2024-12-06 09:33 UTC, kjmjh commented
> xswl，你这个PR属实逆天（）
> 我刚看了下，只有开始菜单能自动收回的。你要做就把搜索、小组件，控制中心和日历都做上啊（）

忘了😶

2024-12-06 18:55 UTC, ProgramCX commented
> 我还用学校微机室的ly电脑试了，没问题
是edge问题